config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :views
  devise_for :users
  root :to => 'blogs#index'

  resources :blogs do
    resources :comments, :except =>[:show, :index]
  end

  namespace :api do
    resources :blogs, :users, defaults: {format: :json}
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :comments
  validates :title, :presence => true
  validates :body, :presence => true

  def channel
    "blogs"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blog

  validates :name, :presence => true
  validates :body, :presence => true
  before_create :send_sms

  private
  begin
    def send_sms
      RestClient::Request.new(
      :method => :post,
      :url => 'https://api.twilio.com/2010-04-01/Accounts/' + ENV['TWILIO_ACCOUNT_SID'] + '/Messages.json',
      :user => ENV['TWILIO_ACCOUNT_SID'],
      :password => ENV['TWILIO_ACCOUNT_AUTH_TOKEN'],
      :payload => {
        :Body => name + ' had something to say about ' + blog.title + '!',
        :From => ENV['TWILIO_ACCOUNT_PHONE_NUMBER'],
        :To => '5034422592' }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    protect_from_forgery with: :null_session
    before_action :set_resource, only: [:destroy, :show, :update]
    respond_to :json

def create
  set_resource(resource_class.new(resource_params))

  if get_resource.save
    render :show, status: :created
  else
    render json: get_resource.errors, status: :unprocessable_entity
  end
end

# DELETE /api/{plural_resource_name}/1
def destroy
  get_resource.destroy
  head :no_content
end

# GET /api/{plural_resource_name}
def index
  plural_resource_name = "@#{resource_name.pluralize}"
  resources = resource_class.where(query_params)
                            .page(page_params[:page])
                            .per(page_params[:page_size])

  instance_variable_set(plural_resource_name, resources)
  respond_with instance_variable_get(plural_resource_name)
end

# GET /api/{plural_resource_name}/1
def show
  respond_with get_resource
end

# PATCH/PUT /api/{plural_resource_name}/1
def update
  if get_resource.update(resource_params)
    render :show
  else
    render json: get_resource.errors, status: :unprocessable_entity
  end
end



    private

      # Returns the resource from the created instance variable
      # @return [Object]
      def get_resource
        instance_variable_get("@#{resource_name}")
      end

      # Returns the allowed parameters for searching
      # Override this method in each API controller
      # to permit additional parameters to search on
      # @return [Hash]
      def query_params
        {}
      end

      # Returns the allowed parameters for pagination
      # @return [Hash]
      def page_params
        params.permit(:page, :page_size)
      end

      # The resource class based on the controller
      # @return [Class]
      def resource_class
        @resource_class ||= resource_name.classify.constantize
      end

      # The singular name for the resource class based on the controller
      # @return [String]
      def resource_name
        @resource_name ||= self.controller_name.singularize
      end

      # Only allow a trusted parameter "white list" through.
      # If a single resource is loaded for #create or #update,
      # then the controller for the resource must implement
      # the method "#{resource_name}_params" to limit permitted
      # parameters for the individual model.
      def resource_params
        @resource_params ||= self.send("#{resource_name}_params")
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_resource(resource = nil)
        resource ||= resource_class.find(params[:id])
        instance_variable_set("@#{resource_name}", resource)
      end
  end
end

app/controllers/api/blogs_controller.rb
module Api
  class BlogsController < Api::BaseController

    private

      def blog_params
        params.require(:blog).permit(:title)
      end

      def query_params
        # this assumes that an blog belongs to an user and has an :user_id
        # allowing us to filter by this
        params.permit(:user_id, :title)
      end

  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < Api::BaseController

    private

      def user_params
        params.require(:user).permit(:email)
      end

      def query_params
        params.permit(:email)
      end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  after_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Request-Method'] = '*'
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @blogs = Blog.all
    render :index
  end

  def show
    @blog = Blog.find(params[:id])
    render :show
  end

  def new
    @blog = Blog.new
    render :new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to blogs_path

      Pusher['blogsChannel'].trigger('new-blog', {
        blog: @blog
      })
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
    render :edit
  end

  def update
    @blog= Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path

      Pusher['blogsChannel'].trigger('new-blog', {
        blog: @blog
      })
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    flash[:notice] = "Blog successfully deleted."
    redirect_to blogs_path

    Pusher['blogsChannel'].trigger('delete-blog', {
      blog: @blog
    })

  end

  private
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new
  end

  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)
    if @comment.save
      flash[:notice] = "Comment successfully added!"

      respond_to do |format|
        format.html {redirect_to blog_path(@comment.blog)}
        format.js
      end

    else
      render :new
    end
  end


  def edit
    @blog = Blog.find(params[:blog_id])
    @comment = Comment.find(comment_params)
    render :edit
  end

  def update
    @blog = Blog.find(params[:blog_id])
    @comment= Comment.find(params[:id])
    if @comment.update(params[:comment])
      redirect_to blog_path(@blog)
    else
      render :edit
    end
  end


  def destroy
    @blog = Blog.find(params[:blog_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment successfully deleted."
    redirect_to blog_path(@blog)
  end

private
  def comment_params
    params.require(:comment).permit(:name, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/_form.html.erb
<%= render "layouts/errors", :object => @blog %>

<%= form_for @blog do |f| %>
  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </p>

  <p>
  <%= f.label :body %>
  <%= f.bootsy_area :body, class: 'form-control', rows: '20' %>
  </p>

  <p>
  <%= f.submit %>
  </p>
  
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit blog</h1>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>
<p><%= link_to "Write a new blog", new_blog_path %></p>

<ul>
  <% @blogs.each do |blog| %>
    <li><%= link_to blog.title, blog_path(blog) %></li>
  <% end %>
</ul>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<h1><%= @blog.title %></h1>

<%= @blog.body %>

<h4>Comments:</h4>
<p>
  <%= link_to "Return to Bloggor index", blogs_path %> |
  <%= link_to "Edit this Blog", edit_blog_path %> |
  <%= link_to "Delete this Blog", blog_path(@blog), :data=> {:method => "delete"} %> |
  <%= link_to "Add a comment", new_blog_comment_path(@blog), id: "new_comment", :remote => true %>
</p>

<ul id="comment_list">
<% if @blog.comments.any? %>

  <% @blog.comments.each do |comment| %>
   <li>
     <%= comment.name %>
     <br>
     <p>
     <%= comment.body %>
     </p>
     <br>
    <%= link_to "Edit this Comment", edit_blog_comment_path(@blog, comment) %> |
    <%= link_to "Delete this comment", blog_comment_path(@blog, comment), :data => {:method => "delete"} %>
   </li>
  <% end %>
  </ul>
  <% else %>
  <p>There are no comments yet!</p>
<% end %>

app/views/comments/_form.html.erb
<div id="new_comment_form">
  <%= render('layouts/errors', :object => @comment) %>

  <%= form_for [@blog, @comment], :remote => true do |f| %>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :body %>
      <%= f.text_field :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>

  <% end %>

</div>

app/views/comments/create.js.erb
$('#new_comment_form').remove();
$('#new_comment').show();
$('#comment_list').append('<%= @comment.body %>');

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<% content_for(:name, "New Comment | Blog") %>

<h1>New comment for <%= @blog.title %></h1>

<%= render 'form' %>

app/views/comments/new.js.erb
$('#new_comment').hide().after('<%= j render("form")  %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloggor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  hello <%= current_user.email %>! |
  <%=link_to "edit profile", edit_user_registration_path %> |
  <%=link_to "logout", destroy_user_session_path, method: :delete %> |
<% else %>
  <%=link_to "Sign up", new_user_registration_path, id: "new_user"%> |
  <%=link_to "Login", new_user_session_path, id: "login" %>
<% end %>

<%= flash[:notice] %>
<%= yield %>

</body>
</html>